### ISSUE TITLE
ArgumentError in BetManager.rb:114:in `award_pot'

### ISSUE THREAD

**Issue by amar47shah** [HaysHopkins/card_games#5]
This is the full output of a game that ended in a runtime error.

```
➜  card_games git:(master) ruby texas_holdem/TexasHoldemDealer.rb
Hays: [" J♥", " 9♥"]
Computer 1: [" 2♥", " 5♣"]
Computer 2: [" Q♣", " 9♦"]
Computer 3: [" K♠", " 8♦"]
Table: []
------------
------------
Hays: Would you like to bet ('50 - 500'), 'Check', 'Fold'?
50
Computer 1: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Call
Computer 2: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Call
Computer 3: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Call
Hays: [" J♥", " 9♥"]
Computer 1: [" 2♥", " 5♣"]
Computer 2: [" Q♣", " 9♦"]
Computer 3: [" K♠", " 8♦"]
Table: [" 2♣", " 8♥", " 8♣"]
------------
------------
Hays: Would you like to bet ('50 - 500'), 'Check', 'Fold'?
Fold
Computer 1: Would you like to bet ('50 - 500'), 'Check', 'Fold'?
50
Computer 2: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Call
Computer 3: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Call
Computer 1: [" 2♥", " 5♣"]
Computer 2: [" Q♣", " 9♦"]
Computer 3: [" K♠", " 8♦"]
Table: [" 2♣", " 8♥", " 8♣", " 4♣"]
------------
------------
Computer 1: Would you like to bet ('50 - 500'), 'Check', 'Fold'?
50
Computer 2: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Fold
Computer 3: Would you like to 'Call' the bet of 50, re-raise ('50 - 500'), or 'Fold'?
Call
Computer 1: [" 2♥", " 5♣"]
Computer 3: [" K♠", " 8♦"]
Table: [" 2♣", " 8♥", " 8♣", " 4♣", " A♣"]
------------
------------
Computer 1: Would you like to bet ('50 - 500'), 'Check', 'Fold'?
Fold
/Users/amar/Code/NonSP/card_games/BetManager.rb:114:in `award_pot': wrong number of arguments (given 0, expected 1) (ArgumentError)
    from texas_holdem/TexasHoldemDealer.rb:102:in `determine_winner'
    from texas_holdem/TexasHoldemDealer.rb:48:in `the_river'
    from texas_holdem/TexasHoldemDealer.rb:127:in `<main>'
```

**Comment by HaysHopkins** [comment]
Fixed--in a manner of speaking!  It still isn't functioning correctly, but no error.  Left my code in the lurch last night to grab some food.
